version: "3.8"
services:

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_default
volumes:
  db:
    driver: local
networks:
  app_default:
    name: app_default
    driver: bridge

